nsqd:
  image: nsqio/nsq:v0.3.8
  command: /nsqd -broadcast-address=127.0.0.1 -lookupd-tcp-address=nsqlookupd:4160
  links:
    - nsqlookupd
  ports:
    - 4150:4150
    - 4151:4151

nsqlookupd:
  image: nsqio/nsq:v0.3.8
  command: /nsqlookupd
  ports:
    - 4160:4160
    - 4161:4161

postgres:
  build: .docker/postgres
  ports:
    - 5432:5432

redis:
  image: redis:alpine
  ports:
    - 6379:6379
